name: T2
module_name: T2
version: 0.10
abstract: Object Relational mapping/persistence system
author: Sam Vilain <samv.org>
license: unknown
distribution_type: module
requires:
  Test::More: 0
  Tangram: 2.07
  Class::Tangram: 1.56
  Set::Object: 1.04
  Storable: 2.07
  DBI: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.39
